const question = document.querySelector('#question')
const choices = Array.from(document.querySelectorAll('.choice-text'))
const progressText = document.querySelector('#progressText')
const scoreText = document.querySelector("#score")

let currentQuestion = {}
let acceptingAnswers = true
let score = 0
let questionCounter = 0
let availableQuestions = []

let questions = [
    {
        question: 'A bird of prey in captivity requires what kind of diet?',
        choice1: "Cooked, well-seasoned, lean meat.",
        choice2: "A diet closely resembling that which it would be eating in the wild.",
        choice3: "A grain mix you can buy from the feed store, supplemented with fresh meat.",
        choice4: "Raptors are omnivores, so they eat all types of food to stay healthy.",
        answer: 2,
    },
    {
        question: 'You must have facilities for the raptor you will fly in the sport of falconry inspected and approved by the VDWR before you get your apprentice permit.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 1,
    },
    {
        question: 'The federal government has done studies that indicate:',
        choice1: "the best bird for an apprentice falconer to have is a Cooper’s hawk.",
        choice2: "apprentices do fine in the sport of falconry, even if they do not have a sponsor.",
        choice3: "the sport of falconry has no impact on the wild raptor populations in the US.",
        choice4: "the best beginning falconers have come from a hunting lifestyle.",
        answer: 3,
    },
    {
        question: 'A potential sponsor requires the following before he or she will agree to shepherd an apprentice into the sport:',
        choice1: "payment for his/her tutelage from the apprentice.",
        choice2: "specific evidence of a sincere commitment on the part of the potential apprentice to undertake all aspects of learning about the sport.",
        choice3: "a note from the potential apprentice’s spouse or parent that it’s okay with him/her if the aspirant undertakes the sport.",
        choice4: "attendance at all VFA events, and help with cleaning the sponsor’s raptor facilities.",
        answer: 2,
    },
    {
        question: 'Not all land is suited to flying a bird of prey, no matter how much prey might be found there. Which of the following would make an ethical, safe falconer consider NOT flying a bird?',
        choice1: "Property where the best prey habitat runs along a busy road.",
        choice2: "An enormous tract of land with plenty of habitat, but where the falconer does not have permission.",
        choice3: "A semi-suburban area or industrial park property where a cat is visible, prowling the brush.",
        choice4: "All of the above.",
        answer: 4,
    },
    {
        question: 'It’s perfectly all right to use raptors permitted under a falconry license for personal gain. Many falconers allow their birds to make paid appearances in films and commer- cials to help support their falconry.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 2,
    },
    {
        question: 'The two most important characteristics of a personality capable of becoming a good falconer are',
        choice1: "curiosity and a mindset that includes lifelong learning.",
        choice2: "stubbornness and a tendency to judge others.",
        choice3: "patience and persistence.",
        choice4: "a and c only.",
        answer: 4,
    },
    {
        question: 'The definition of falconry is',
        choice1: "the pursuit of wild game in its natural habitat by means of a trained bird of prey.",
        choice2: "holding a bird on the glove and attending renaissance fairs.",
        choice3: "using a better-than-average knowledge of raptor biology to rehabilitate birds of prey so they can return to the wild.",
        choice4: "doing educational presentations surrounding birds of prey, their habitats, conservation, biology, and natural history for groups from scouts to bird watchers.",
        answer: 1,
    },
    {
        question: 'The methods used for training a bird of prey are just like those used in training a hunting dog or a hunter/jumper horse.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 2,
    },
    {
        question: 'Which of the following is the best approach to the various pieces and styles/types of equipment used in falconry?',
        choice1: "Make everything you will use in falconry, from facilities to gauntlets; from hoods to swivels.",
        choice2: "Caring for and maintaining the equipment you cannot make yourself.",
        choice3: "Annually replacing any equipment that is attached to the bird for safety’s sake.",
        choice4: "b and c above.",
        answer: 4,
    },
    {
        question: 'Falconry permits in the United States are regulated, administered, and enforced by each state or territory’s game department. All of these agencies have different names, and to find your state’s department, search for the group that manages hunting licens- es. In the Commonwealth of Virginia, our regulating agency is which of the following?',
        choice1: "The federal Fish and Wildlife Service.",
        choice2: "The Virginia Army Reserves.",
        choice3: "Officials at the university nearest where you live.",
        choice4: "The Department of Wildlife Resources.",
        answer: 4,
    },
    {
        question: 'The falconry exam consists of 105 questions in several categories of study. While it is not necessary to know arcane terminology or the titles of ancient texts, it is good to focus your study in the areas of concentration in the test. Among these categories are which of the following?',
        choice1: "Definitions and regulations.",
        choice2: "Biology and habitat of prey species.",
        choice3: "Training and hunting.",
        choice4: "a and c only.",
        answer: 4,
    },
    {
        question: 'To pass the exam, you must know the scientific names of species.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 2,
    },
    {
        question: 'Among the most important aspects of becoming a falconer is to build and have inspected the housing where your raptor will live. Housing must be safe for the bird in terms of perching materials and tethering systems (where chosen). Privacy for the bird is important, as well as air flow for summer cooling, yet wind protection for winter warmth. To pass inspection, a mew must',
        choice1: "have a secure door easily closed.",
        choice2: "have a floor that pools with water.",
        choice3: "be difficult to access, because that assures raptor safety",
        choice4: "assure no predators or neighborhood children can get inside, thus cannot have any windows.",
        answer: 1,
    },
    {
        question: 'The nongame biologist assigned to your region will come and administer the test at the same time he/she inspects your housing and equipment. Among the items of equipment required to be presented at the time of inspection, you will need the following:',
        choice1: "sturdy hunting boots.",
        choice2: "a beating stick for flushing game.",
        choice3: "all of the above.",
        choice4: "none of the above.",
        answer: 4,
    },
    {
        question: 'There is much tradition surrounding the sport of falconry, and many pieces of tradi- tional equipment as well as the ways of making them have endured through centuries. A good example is a piece of leather we call a “bewit,” an item of equipment used for attaching:',
        choice1: "bells around the neck",
        choice2: "bells or transmitters to the legs.",
        choice3: "jesses to the bird’s tarsi",
        choice4: "a swivel to the jesses.",
        answer: 2,
    },
    {
        question: 'There are many items that will be required before you get your first bird. Which of the following is NOT required for a newly-trapped raptor?',
        choice1: "A glove.",
        choice2: "A swivel",
        choice3: "A transmitter.",
        choice4: "A leash",
        answer: 3,
    },
    {
        question: 'Before entering the sport, it is good to have a working knowledge of the rules, laws, ethics, and regulations governing falconry. Having a copy of the falconry regulations adopted by your state is an essential piece of reference material. For example, each level of permittee in falconry offers different privileges. Having learned these permittee levels, you know that apprentice falconers are allowed to have an imprinted bird only',
        choice1: "if it is a red-tailed hawk.",
        choice2: "with your sponsor’s approval and permission",
        choice3: "if it is given to you by a rehabilitator.",
        choice4: "none of the above",
        answer: 4,
    },
    {
        question: 'Any Virginia resident who applies for a falconry permit can substitute a minimum of 4 months and a maximum of 1 year of education from a certified falconry school and/or volunteer work at a raptor rehabilitation center for a portion of his or her 2-year appren- ticeship in the sport of falconry.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 2,
    },
    {
        question: 'In addition to the equipment that will be attached directly to the bird, the inspection checklist includes several other pieces of equipment. A bath pan, however, is not nec- essary because',
        choice1: "birds of prey don’t like to bathe.",
        choice2: "raptors don’t drink much because they get all the hydration they need from eating fresh meat.",
        choice3: "a full bath pan could cause illness in a bird.",
        choice4: "none of the above.",
        answer: 4,
    },
    {
        question: 'Which factor is most important in determining which raptor any falconer should fly?',
        choice1: "Legal status of the falconer.",
        choice2: "Proximity to other falconers flying similar species.",
        choice3: "Availability of prey suitable for that raptor.",
        choice4: "Appropriateness of raptor housing.",
        answer: 3,
    },
    {
        question: 'Apprentice falconers are not allowed to take eyass birds for use in falconry.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 1,
    },
    {
        question: 'Traveling with your bird is often a key element of the sport. Even if you have your own acreage, you don’t want to “overhunt” the population of game species on your own grounds. So falconers most often have permissions at several friends’ and neigh- bors’ properties where they carry their birds to fly on game. To practice falconry on other properties where they have permission to hunt, many falconers use a giant hood, which is. ',
        choice1: "a transport box built to fit the size and perch needs of a trained raptor.",
        choice2: "a large leather hood primarily used for big raptors such as eagles.",
        choice3: "good to keep a hood-shy raptor calm.",
        choice4: "a and c are correct",
        answer: 4,
    },
    {
        question: 'Because this all-important piece of equipment is so critical, it is important that you use the best possible style of swivel. The best swivel to have in a leash/jess system is',
        choice1: "a French clip.",
        choice2: "one with a strong ball bearing “works.”",
        choice3: "any snap-type will do.",
        choice4: "all of the above.",
        answer: 2,
    },
    {
        question: 'All leash/jess systems have a swivel involved. Even if your housing is not designed to use a tethering option, there will be times that you tie your bird’s leash to a bow or ring perch, into its giant hood, or via another arrangement. The swivel is essential for which of the following reasons?',
        choice1: "So the bird will not fly away.",
        choice2: "So your bird will not twist its jesses and tangle its feet and legs in a knot.",
        choice3: "So it won’t be attacked by a wild raptor.",
        choice4: "So it will remain calm and stress-free.",
        answer: 2,
    },
    {
        question: 'Your sponsor will guide your choice of which type of leash/jess system you will adopt. Many experienced falconers make their own equipment and your sponsor might require you to do so as well. The leash a falconer uses in the sport may be',
        choice1: "made of well-oiled, strong leather.",
        choice2: "made of strong-yet-supple nylon.",
        choice3: "be directly attached to the tarsus.",
        choice4: "a and b are correct.",
        answer: 4,
    },
    {
        question: 'If we break the laws or ignore the regulations surrounding falconry set by our reg- ulating agency, and we are caught doing so, the Law Enforcement arm of that agency has the authority to revoke permits and confiscate birds. Which agency regulates and monitors the sport of falconry in the United States, and is responsible for suspension or revocation of permits to practice falconry?',
        choice1: "The federal Fish and Wildlife Service (FWS).",
        choice2: "The agency authorized by the state, tribal, or territorial government where the applicant/permittee resides.",
        choice3: "The department of motor vehicles (DMV) in the state where the applicant/permittee resides.",
        choice4: "None of the above.",
        answer: 2,
    },
    {
        question: 'If an apprentice falconer moves to another state in the middle of his/her appren- ticeship and keeps the permit from the state he/she left while applying for a second permit in the new residence, then the apprentice can have any number of falconry permits, and can possess the number of raptors allowed by each permit.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 2,
    },
    {
        question: 'Due to their size and overall biology and habitat, Cooper’s hawks are best suited for hunting',
        choice1: "jackrabbits.",
        choice2: "quail.",
        choice3: "ducks.",
        choice4: "pheasant.",
        answer: 2,
    },
    {
        question: 'Tiercel sharp-shinned hawks have all the skills needed for hunting',
        choice1: "rabbits.",
        choice2: "ducks.",
        choice3: "English sparrows.",
        choice4: "quail.",
        answer: 3,
    },
    {
        question: 'In the Western US, there’s a buteo that feeds primarily on ground quarries (like black-tailed jackrabbits) called the ferruginous hawk. Having read a little about ferrugs, you know that they',
        choice1: "won’t defend the nest because it’s near the ground.",
        choice2: "are parabuteos.",
        choice3: "tend to be larger than a red-tailed hawk.",
        choice4: "b and c above.",
        answer: 3,
    },
    {
        question: 'A kestrel’s ideal hunt-able quarry in Virginia is',
        choice1: "quail.",
        choice2: "starlings.",
        choice3: "English sparrows.",
        choice4: " b and c above.",
        answer: 4,
    },
    {
        question: 'In the US, goshawks, Cooper’s hawks, and sharp-shinned hawks (accipiters) are also called',
        choice1: "broad wings.",
        choice2: "long wings.",
        choice3: "short wings.",
        choice4: "all of the above.",
        answer: 3,
    },
    {
        question: 'In general, the male birds of prey',
        choice1: "are first to return from migration.",
        choice2: "select the nesting/egg-laying area.",
        choice3: "provide most of the food after the young have hatched.",
        choice4: "all of the above.",
        answer: 4,
    },
    {
        question: 'After a strenuous fight with a squirrel during hunting, you discover that your RTH has bent a tail feather. What should you do about this?',
        choice1: "Cut it off at the bend and imp a new feather in its place.",
        choice2: "Call your sponsor and ask for advice.",
        choice3: "Soak the feather in leather softening oil.",
        choice4: "Pluck the feather from the bird’s body so it will grow back during the summer.",
        answer: 2,
    },
    {
        question: 'As you administer feather mite spray to your newly-trapped bird, you notice visible lines along the shafts of the wing feathers, all about the same spot on several prima- ries. These marks might be “fret marks” and indicate which of the following:',
        choice1: "arrested feather development.",
        choice2: "stress.",
        choice3: "both a and b.",
        choice4: "none of the above.",
        answer: 3,
    },
    {
        question: 'Any passage hawk in captivity is most likely to break tail feathers',
        choice1: " if the falconer uses a tail saver on his/her bird.",
        choice2: "if the bird normally crashes into brush to catch rabbits.",
        choice3: "if it is housed improperly or kept on a perch wrong for its speci",
        choice4: "when it is allowed to warble.",
        answer: 3,
    },
    {
        question: 'Knowing the stages of a raptor’s life are important identification techniques, and the terminology used for thousands of years in falconry is helpful in designating those stages. Which of the statements below is/are true:',
        choice1: "A haggard hawk was once an eyass.",
        choice2: "An eyass hawk was once a haggard.",
        choice3: "A passage bird was once an eyass.",
        choice4: "a and c above are true.",
        answer: 4,
    },
    {
        question: 'Which of the birds of prey listed is most likely to travel the longest distance during its migratory period?',
        choice1: "Merlin.",
        choice2: "Prairie falcon.",
        choice3: "Goshawk.",
        choice4: "Gyrfalcon.",
        answer: 1,
    },
    {
        question: 'In general, a bird of prey will have reached full size by the time it is',
        choice1: "1 year old.",
        choice2: "fledging from the nest.",
        choice3: "about breeding age, around 2-3 years old.",
        choice4: "halfway through its first year.",
        answer: 2,
    },
    {
        question: 'Which among the following list of birds of prey is the LEAST likely to raise its young on a cliff or rock ledge?',
        choice1: "Jerkin.",
        choice2: "Golden eagle.",
        choice3: "Prairie falcon.",
        choice4: "Jack",
        answer: 4,
    },
    {
        question: 'A young peregrine falcon might fledge from its scrape when it is',
        choice1: "six to seven weeks of age.",
        choice2: "two to three months of age.",
        choice3: "twelve to fourteen weeks of age.",
        choice4: "pushed out of the scrape by its siblings.",
        answer: 1,
    },
    {
        question: 'Large falcons have a particular style of capturing their prey. For the most part, they',
        choice1: "strike their prey in mid-air, knocking it senseless.",
        choice2: "bind to their prey and carry it to the nest.",
        choice3: "come up from below once the prey is in flight.",
        choice4: "a and b are both options chosen by peregrines to capture prey.",
        answer: 4,
    },
    {
        question: 'Due to their native habitat and the construction of their feet, which of the following types of perch is best suited for tethering a red-tailed hawk outdoors?',
        choice1: "Screen perch.",
        choice2: "Block perch.",
        choice3: "A ring perch.",
        choice4: "None of the above",
        answer: 3,
    },
    {
        question: 'A block perch is best suited to which type of raptor?',
        choice1: "Goshawk.",
        choice2: "Red-tailed hawk.",
        choice3: "Falcon.",
        choice4: "Red-shouldered hawk.",
        answer: 3,
    },
    {
        question: ' Our largest North American accipiter, the goshawk, most often lives and breeds in what type of habitat?',
        choice1: "In suburban woodlots.",
        choice2: "In the edge of a woodlot near open meadows.",
        choice3: "In a coniferous forest.",
        choice4: "On cliffs",
        answer: 3,
    },
    {
        question: 'Falconers are allowed to receive native raptor feathers from others who are specially permitted to handle raptors (rehabilitators, breeders); and falconers are allowed to give feathers to permitted raptor handlers.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 1,
    },
    {
        question: 'Though rare in the wild, parabuteos in the sport of falconry in North America as well as in Europe',
        choice1: "are best suited for hunting exotic quarry, since they’re rather exotic themselves.",
        choice2: "may be hunted in groups.",
        choice3: "are often avoided because they are challenging to get to work with humans.",
        choice4: "exhibit none of the above characteristics.",
        answer: 2,
    },
    {
        question: 'Some raptors are more adapted to cold weather than others. Which of the birds listed below are most cold-tolerant?',
        choice1: "Red-tailed hawk.",
        choice2: "Harris’ hawk.",
        choice3: "Aplomado falcon.",
        choice4: "None of the above.",
        answer: 1,
    },
    {
        question: 'Some falconers use scales that weigh in grams and others use scales that weigh in ounces. A gram scale is appropriate for which of the following?',
        choice1: "Peregrine falcons.",
        choice2: "American Kestrels.",
        choice3: "Red-tailed hawks.",
        choice4: "All of the above.",
        answer: 4,
    },
    {
        question: 'Some species of raptor are more heat-tolerant than others. Shade from direct sunlight in outdoor summertime housing',
        choice1: "is usually not necessary because raptors rarely need it.",
        choice2: "is the best way for them to get vitamin D.",
        choice3: "is necessary because a raptor runs the risk of overheating.",
        choice4: "a and b above.",
        answer: 3,
    },
    {
        question: 'Some falconers find all birds are easy to “man.” But which of the following has the reputation for being the easiest raptor to man?',
        choice1: "The passage goshawk.",
        choice2: "The passage prairie falcon.",
        choice3: "The passage red-tai.",
        choice4: "The passage sharp-shinned hawk.",
        answer: 3,
    },
    {
        question: 'Selection of your first bird’s species is critical. The reason to choose an American kestrel over a red-tailed hawk as your hunting partner is because',
        choice1: "they are easier to keep healthy.",
        choice2: "they don’t require as much food.",
        choice3: "they are less likely to carry their prey.",
        choice4: "none of the above.",
        answer: 4,
    },
    {
        question: 'Each species of raptor has a “signature” hunting style. For a red-tailed hawk this style can be described as',
        choice1: "waiting-on.",
        choice2: "a close-fisted strike from above.",
        choice3: "sit-and-wait.",
        choice4: "none of the above.",
        answer: 3,
    },
    {
        question: 'Because male raptors are a third smaller than females, a male red-tailed hawk is preferred for falconry because',
        choice1: "the females are too big and slow to take squirrels.",
        choice2: "they are very agile and will take jackrabbits more easily.",
        choice3: "they are calmer, less aggressive, and easier to man.",
        choice4: "None of the above.",
        answer: 4,
    },
    {
        question: 'Of the following, the raptor most likely to kill quarry with its powerful grip is',
        choice1: "a jack.",
        choice2: "a jerkin.",
        choice3: "a red-tail.",
        choice4: "a kestrel.",
        answer: 3,
    },
    {
        question: 'A female kestrel is preferred over a male kestrel because',
        choice1: "they train more easily.",
        choice2: "females can handle English sparrows better.",
        choice3: "overall the larger females simply hunt better.",
        choice4: "None of the above.",
        answer: 4,
    },
    {
        question: 'Every falconer must keep excellent records of birds in and out of his/her posses- sion. The law states that you must have all permits and paperwork (or copies of them) in your possession whenever you and your bird(s) are not at the location of your fal- conry facilities. This means “on your person” if you are trapping, transporting (even to educational activities) working with, flying, or hunting your falconry raptors.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 1,
    },
    {
        question: 'Merlins and American kestrels resemble one another in some respects. What among the following are cues to ID these two small falcons?',
        choice1: "A merlin is stockier in build than the more streamlined kestrel.",
        choice2: "Merlins typically are somewhat darker brown than the less colorful female kestrels.",
        choice3: "Where kestrels have an irregular pattern of wing beats and glides, a merlin has a snappy, near-constant wingbeat pattern.",
        choice4: "All of the above.",
        answer: 4,
    },
    {
        question: 'Juvenile red-tailed hawks don’t have a red tail. But a more subtle way of IDing a juvenile RTH is to look for',
        choice1: "a “belly band.”",
        choice2: "a very light colored head.",
        choice3: "a circular white area at the top of the breast.",
        choice4: "a and c above",
        answer: 4,
    },
    {
        question: 'The malar patch is typical of many',
        choice1: "species of falcon.",
        choice2: "accipitrine birds.",
        choice3: "prairie chickens.",
        choice4: "hawk species.",
        answer: 1,
    },
    {
        question: 'Smaller birds, especially, but any raptor might carry its food to a safer, higher perch when it feels especially vulnerable.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 1,
    },
    {
        question: 'Of those listed, the raptor most likely to engage in a ringing flight style is the',
        choice1: "goshawk.",
        choice2: "merlin",
        choice3: "kestrel",
        choice4: "red-tail",
        answer: 2,
    },
    {
        question: 'You find a compact “pellet” under your bird’s perch in the morning. But you know what to do because you’ve learned that this is',
        choice1: "the first sign of frounce.",
        choice2: "a normal bowel movement.",
        choice3: "a foul smelling bacterial infection.",
        choice4: "the indigestible portion of the raptor’s last meal.",
        answer: 4,
    },
    {
        question: 'The apprentice falconer needs to judge his or her raptor’s condition daily by',
        choice1: "checking feather condition.",
        choice2: "weighing.",
        choice3: "feeling the keel.",
        choice4: "checking for yarak.",
        answer: 2,
    },
    {
        question: 'A green mute or slice may indicate',
        choice1: "a healthy bird that has not eaten for 36 hours.",
        choice2: "aspergillosis.",
        choice3: "coccidiosis.",
        choice4: "either a or b above",
        answer: 4,
    },
    {
        question: 'Flying your bird in the vicinity of power poles that have transformers or other structures that might tempt a bird to use them as a perch while hunting',
        choice1: "is fine as long as you obtain permission before entering the vicinity.",
        choice2: "poses a significant risk of electrocution.",
        choice3: "an cause the bird to “slip.”",
        choice4: "none of the above.",
        answer: 2,
    },
    {
        question: 'A bell or a pair of bells, whether attached to the tail or the tarsi, is a good tool for the falconer to use',
        choice1: "while hunting.",
        choice2: "while weathering.",
        choice3: "while trapping.",
        choice4: "a and b above.",
        answer: 4,
    },
    {
        question: 'A good diet is essential to the health of a bird in captivity. A falconer has nearly com- plete control over the diet of his/her raptor, except when it is hunting, where problems can sometimes occur. What if your bird eats a wild pigeon while you’re in the field? Eating a feral pigeon places your bird at risk of catching',
        choice1: "frounce.",
        choice2: "avian herpes virus.",
        choice3: "Aspergillosis.",
        choice4: "both a and b",
        answer: 4,
    },
    {
        question: 'When a raptor drinks water, it’s called',
        choice1: "yarak.",
        choice2: "bowsing.",
        choice3: "warbling.",
        choice4: "carrying.",
        answer: 2,
    },
    {
        question: 'A brown lump in your hawk’s slice is surrounded by a white chalky substance. What is this white stuff?',
        choice1: "rates from the kidneys.",
        choice2: "Feces from the digestive tract.",
        choice3: "Abnormal and cause for concern.",
        choice4: "Undigested food.",
        answer: 1,
    },
    {
        question: 'Aspergillosis is one of the “Big Five” to watch for. In most cases, once you see symptoms, it is too late to treat. Asper primarily affects what group or system?',
        choice1: "Digestive.",
        choice2: "Respiratory.",
        choice3: "Nervous.",
        choice4: "Molt/feathers.",
        answer: 2,
    },
    {
        question: 'A raptor’s housing must provide',
        choice1: "protection from predators",
        choice2: "protection from the elements",
        choice3: "good ventilatio",
        choice4: "all of the above",
        answer: 4,
    },
    {
        question: 'The terms “passage” “imprint” and “chamber” describe:',
        choice1: "the legal status of the falconer.",
        choice2: "the nature of the mews area in which a raptor is kept.",
        choice3: "how the raptor was raised.",
        choice4: "none of the above.",
        answer: 3,
    },
    {
        question: 'A relaxed hawk is likely to',
        choice1: "preen.",
        choice2: "raise and tuck one foot.",
        choice3: "rouse.",
        choice4: "all of the above.",
        answer: 4,
    },
    {
        question: 'As one of the “Big Five,” Asper is most often found among which raptors?',
        choice1: "Gyrfalcons.",
        choice2: "Peregrines.",
        choice3: "Red-tailed hawks.",
        choice4: "Any of the above.",
        answer: 4,
    },
    {
        question: 'There are many communicable diseases to which raptors are susceptible, and many arise from eating meat of unknown origin from a specific group of wild birds: pigeons and doves. The most common disease transmitted between, say, mourning doves and raptors is',
        choice1: "asper.",
        choice2: "coccidiosis.",
        choice3: "frounce.",
        choice4: "pneumonia.",
        answer: 3,
    },
    {
        question: 'Watching your bird’s behaviors, and what comes out of your bird are key to know- ing when it is sick. It is good to be familiar with your individual bird’s behaviors and “normals” so you can tell when it “goes off.” Knowing this, you watch your bird feak after eating, and it warbles on its perch. It tends to stand on one leg. These behaviors indicatea.',
        choice1: "sour crop.",
        choice2: "that it’s time to call your sponsor for advice because symptoms of illness are present.",
        choice3: "a content and healthy bird.",
        choice4: "West Nile virus.",
        answer: 3,
    },
    {
        question: 'Any equipment attached directly to the bird must be fashioned and monitored care- fully. A bracelet or anklet that is cut too narrowly may cause',
        choice1: "excessive bating.",
        choice2: "damage to the tarsi.",
        choice3: "damage to the cere.",
        choice4: "a hanging alula.",
        answer: 2,
    },
    {
        question: 'Bad things can happen while you’re out hunting your bird. Squirrel bites, sprained or stressed wings, and more. What if your bird crashes thick cover and emerges fa- voring its leg? You think it’s broken, but your town doesn’t have an avian vet. The best way to prevent this scenario is',
        choice1: "to never hunt your bird.",
        choice2: "to only fly your bird to the lure.",
        choice3: "to have located a raptor vet before you got a bird.",
        choice4: "to hunt your bird only where there’s no cover.",
        answer: 3,
    },
    {
        question: 'Knowing what a “normal” mute/slice looks and smells like when it comes out of your bird is essential to monitoring its health. What if the bird slices on your kitchen floor, and you notice a white object moving in the urates? You need to',
        choice1: "take the bird to a vet for a fecal float.",
        choice2: "treat with piperazine or another suitable drug to combat internal parasites.",
        choice3: "call your sponsor and ask advice.",
        choice4: "choose among any of the above and act accordingly.",
        answer: 4,
    },
    {
        question: 'Knowing the symptoms of different conditions and diseases can be key to acting quickly enough to save your bird’s life. Cheesy plaques or lesions in the mouth, weight loss, and “food-flicking” are signs of which of the following?',
        choice1: "Coccidiosis.",
        choice2: "Frounce.",
        choice3: "Aspergillosis.",
        choice4: "Apoplexy.",
        answer: 2,
    },
    {
        question: 'What would be your first step in dealing with the following scenario? Your bird is at the low end of its flying weight, so you feed it a large meal. The next day it still has a crop and you notice foul-smelling breath and recognize this as sour crop. First, you should',
        choice1: "extract the contents of the crop.",
        choice2: "administer Pedialyte.",
        choice3: "administer I.V. antibiotics.",
        choice4: "begin an Ancobon regimen.",
        answer: 2,
    },
    {
        question: 'One of the best ways to prevent injuries to your bird while in the field is',
        choice1: "to arrive at the kill site as quickly as possible.",
        choice2: "never to let it walk along the ground.",
        choice3: "always trade the bird off the kill without letting it break in.",
        choice4: "never to allow it to attain a perch more than 80 feet high.",
        answer: 1,
    },
    {
        question: 'During the process of manning a captive raptor, falconers for centuries have used a “tiring” to keep the bird afist, eating something bony and full of tendons, but with not too much meat so it does not get overfed. The use of such a “tiring” serves many pur- poses, including which of the following:',
        choice1: "keeps a bird’s beak trim.",
        choice2: "aids in manning a bird.",
        choice3: "provides a nutritious meal.",
        choice4: "a and b above",
        answer: 4,
    },
    {
        question: 'Any raptor bred in captivity must be banded with a seamless, non-reusable metal band.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 1,
    },
    {
        question: 'Many falconers use field jesses while hunting, or just fly jess-less. It is advisable to use field jesses (as opposed to mews jesses) while hunting because',
        choice1: "they prevent your bird from getting entangled in trees.",
        choice2: "they prevent your bird from leaving the fist when startled.",
        choice3: "they prevent frounce.",
        choice4: "a and b above.",
        answer: 4,
    },
    {
        question: 'A wild raptor comes in and crabs with your bird while you’re hunting it in the woods. When you retrieve your bird you notice blood on its thigh. You should',
        choice1: "give it Pedialyte and apply a bandage to the leg.",
        choice2: "apply a topical antibiotic and take your bird to a vet for further evaluation.",
        choice3: "do a fecal float.",
        choice4: "administer piperazine",
        answer: 2,
    },
    {
        question: 'If you were required to finish the following sentence, which one of the statements below would be false? “Hunters behaving responsibly in public',
        choice1: "patiently answer questions posed by onlookers, whether those people are expected or unexpected.”",
        choice2: "know than an empty farmhouse means no one owns the huntable land surrounding it.”",
        choice3: "eave all gates as they’re found, and don’t damage fencing when crossing permitted borders.”",
        choice4: "keep verbal descriptions of a bird’s flight respectful of the quarry and without profanity.”",
        answer: 2,
    },
    {
        question: 'When the “lead” falconer in the field is attempting to call his/her bird, a visitor should',
        choice1: "stay back and be still.",
        choice2: "not get between the falconer and the bird.",
        choice3: "walk toward the bird to help the falconer find it.",
        choice4: "a and b above.",
        answer: 4,
    },
    {
        question: 'There are many benefits to be realized by hunting your bird frequently. They may include but are not limited to which the following:',
        choice1: "providing a good diet of wild caught game.",
        choice2: "providing excellent exercise for your bird.",
        choice3: "strengthening the bond between you and your bird.",
        choice4: "all of the above.",
        answer: 4,
    },
    {
        question: 'Regulations governing falconry are understood and respected by ethical falconers. Still, the regs are crafted to take into account that a bird of prey knows nothing of laws, property boundaries, or ethics. Which statement below fits the Let it Lay Law?',
        choice1: "When your raptor is mortally wounded in the field, it is best to let it lay and report the death to your sponsor.",
        choice2: "Sometimes, it’s most effective to spot quarry while lying on the ground, and this activity is legal.",
        choice3: "f your bird takes quarry that is illegal, out of season, or on non-permitted property, you can let it feed on the spot, but have to leave the remains on the kill site.",
        choice4: "When your hawk or falcon loses hold of a prey item and it escapes but is wounded, you cannot simply let it go without making every effort to re-acquire the wounded animal.",
        answer: 3,
    },
    {
        question: 'You are learning weight management for your RTH, but the temperatures dropped significantly more overnight than you’d planned for. You think that your hawk appears “too keen,” but you want to go hunting with your sponsor anyway. You should',
        choice1: "give it rangle.",
        choice2: "use a halsband while hunting.",
        choice3: "tame-hack it.",
        choice4: "none of the above.",
        answer: 4,
    },
    {
        question: 'There are risks to free-flying your hawk every day during hunting season because Murphy’s Law seems to apply year-round. But flying your hawk in an educational pre- sentation scheduled for April may be particularly risky because',
        choice1: "hawks are more likely to get electrocuted.",
        choice2: "migratory urges may surface.",
        choice3: "raptors are more likely to warble.",
        choice4: "the game is harder to catch.",
        answer: 2,
    },
    {
        question: 'The first time you fly your RTH is always fraught with stress. But you go ahead and take that “leap of faith,” and your bird refuses to come down from a tree and you are forced to leave it out overnight. Your next step should be to',
        choice1: "call your sponsor and ask for help and advice.",
        choice2: "set up a bow net to the south and try to re-trap it on its migration.",
        choice3: "arrive before dawn the next morning and try to recover it.",
        choice4: "a and c above.",
        answer: 4,
    },
    {
        question: 'Ethical behavior in all walks of life is an important character trait. Taking time to consider the ethics of your actions on a daily basis (or upon reflection) builds character and reputation. A person practicing ethical hunting/falconry',
        choice1: "is as concerned about the environment as the taking of game.",
        choice2: "supports wildlife management practices, for both game and non-game species.",
        choice3: "follows the regulations and hunting laws for the region in which he/she is hunting.",
        choice4: "all of the above.",
        answer: 4,
    },
    {
        question: 'Beginning falconry is hard and there is an incredible amount to learn. Not only are you a newbie, but your bird is, also. Your job is to create opportunities for success for the bird in your care. A RTH will have more success hunting if',
        choice1: "it is hunting from trees or poles.",
        choice2: "you carry it on an elevated T perch.",
        choice3: "you hunt it from the fist.",
        choice4: "a and b above.",
        answer: 4,
    },
    {
        question: 'There are many tools of the falconry trade. Because we’re working with a live, wild animal, sometimes the use of a live-lure (sometimes called “a baggie”) is necessary. Which of the statements below reflect when the circumstances would call for the use of “a baggie?”',
        choice1: "Whenever you’re hunting a goshawk.",
        choice2: "Whenever you’re hunting a red-tail that is too keen and “crashing.”",
        choice3: "Never.",
        choice4: "Only in an emergency.",
        answer: 4,
    },
    {
        question: 'When flown free, a hybrid raptor must have at least two attached radio transmitters to help locate the bird.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 1,
    },
    {
        question: 'Various states have distinct falconry seasons, so it’s good to double-check the legal season if you’re intending to practice falconry. Virginia’s legal falconry season extends from',
        choice1: "April through September.",
        choice2: "October through March.",
        choice3: "the time you’ve trapped and trained your bird through its first molt.",
        choice4: "every year starting in the month when your bird is estimated to have hatched through March 31.",
        answer: 2,
    },
    {
        question: 'Hunting in Virginia is a regulated activity, and falconry is classified as a hunting sport. If you’ve never had a hunting license before',
        choice1: "you will have to undergo hunter education and be certified to have done so.",
        choice2: "your falconry license will cover all the licenses you need.",
        choice3: "the exam you take to get your falconry license will count toward your hunter education.",
        choice4: "none of the above.",
        answer: 1,
    },
    {
        question: 'An ethical falconer',
        choice1: "helps insure a quick, humane kill whenever possible.",
        choice2: "is as satisfied with observing a good flight as he/she is with bagging quarry.",
        choice3: "obtains landowner permission **before** entering private lands.",
        choice4: "all of the above.",
        answer: 4,
    },
    {
        question: 'Hunters in Virginia hold a special status in the Code of Virginia. If a non-hunter interferes with your trap site or your hunt, you',
        choice1: "have no recourse and will just have to go somewhere else.",
        choice2: "can shout and scream at them for messing up your hunt or trap target.",
        choice3: "should tell them politely but firmly that you have the right to do as you’re doing, and they do not have the right to interfere.",
        choice4: "need to immediately call the DWR game officer in your area and explain the situation to him/her.",
        answer: 3,
    },
    {
        question: 'The hunting style of a peregrine falcon has been used, studied, and targeted in training in the sport of falconry for centuries. This style of hunting is traditionally made up of which of the following?',
        choice1: "Long pursuits that last for miles and miles.",
        choice2: "Crashing into heavy brush from treetops.",
        choice3: "Bursts of speed lasting just a short time each.",
        choice4: "Waiting-on flights.",
        answer: 4,
    },
    {
        question: 'Basing your training methods and hunting approach on the natural style of a hunting raptor is the straightest road to success. If your bird is a red-tailed hawk, which of the listed hunting environments might be best for both your bird’s hunting style and finding your intended quarry?',
        choice1: "The boreal forest.",
        choice2: "The grasslands of the prairie.",
        choice3: "Over the Great Lakes.",
        choice4: "All of the above.",
        answer: 2,
    },
    {
        question: 'In nature, the peregrine learns through trial and error (and some lessons from the parents) that it is advantageous to do what is natural and attain a high pitch in the sky for the best opportunity to catch their dinner. In falconry, training a young, captive-bred peregrine falcon to take a pitch is sometimes accomplished by',
        choice1: "training with homing pigeons.",
        choice2: "training with a kite.",
        choice3: "flying ground quarry.",
        choice4: "only a and b above.",
        answer: 4,
    },
    {
        question: 'Provided you’ve chosen your young raptor based on the quarry you have available to you, your new hawk might run across any number of additional prey species in the hunting grounds to which you introduce it. Among the list below, which prey species would be acceptable as quarry for a new hawk to pursue?',
        choice1: "Squirrel.",
        choice2: "Rabbit.",
        choice3: "Quail.",
        choice4: "All of the above.",
        answer: 4,
    },
    {
        question: 'If, after you obtain your general permit and are qualified to do so, you’ve taken the plunge and purchased a large hybrid falcon—and you’re very keen to start it hunting and catching ducks—so you might want to undertake which of the following?',
        choice1: "Fly larger water to encourage a good pitch.",
        choice2: "Fly a single or small group of ducks.",
        choice3: "Encourage your bird to take a duck off the surface of the water.",
        choice4: "None of the above.",
        answer: 2,
    },
    {
        question: 'The learning curve of both new falconers and new raptors in the sport is steep. Among the more difficult aspects of the sport is always maintaining a trusting relation- ship with your bird when it is so easy to unintentionally break that trust. Excitement about the success of your RTH on its first kill can make the process of making in to your bird as it handles its dinner fraught with stress. This is why experience recom- mends you do which of the following when making in:',
        choice1: "proceed deliberately and cautiously.",
        choice2: "avoid the kill site until your bird has eaten its fill.",
        choice3: "get to your bird quickly so you can take the quarry from her and resume hunting.",
        choice4: "leave it to your sponsor.",
        answer: 1,
    },
    {
        question: ' In the long tradition of falconry, several bird species have been employed, depend- ing on the geography in which the sport was practiced. Which of the following is the raptor species most commonly used by falconers during the sixteenth century?',
        choice1: "Red-tailed hawk.",
        choice2: "Harris’ hawk.",
        choice3: "Cooper’s hawk.",
        choice4: "Peregrine falcon.",
        answer: 4,
    },
    {
        question: 'You live in a semi-urban/suburban area and your first bird will have access to non-natives like English sparrows and starlings. You and your sponsor have decided that an American kestrel will be the best bird for you to handle during your apprentice- ship. Because starlings are a challenge for an AK, the best slip on starlings you can set up for your bird will be to',
        choice1: "assure it has a high, waiting-on pitch.",
        choice2: "go into an area where it will have a ringing flight.",
        choice3: "find a group that is bathing and slip from close range.",
        choice4: "forget it because it’s not possible.",
        answer: 3,
    },
    {
        question: 'Many falconers take their RTHs out west to challenge their birds by hunting jack rabbits. This quarry is challenging because',
        choice1: "they seek thick cover.",
        choice2: "they are fast and good at dodging.",
        choice3: "they are big for a red-tail.",
        choice4: "none of the above.",
        answer: 2,
    },
    {
        question: 'In general, all of the accipiters—but especially goshawks and Cooper’s hawks— are most commonly hunted',
        choice1: "from power poles.",
        choice2: "from a commanding pitch.",
        choice3: "from the fist.",
        choice4: "one of the above.",
        answer: 3,
    },
    {
        question: 'Accipiters are fast and agile, and thus, are good raptors to use if you want to hunt upland game birds like pheasant, quail, grouse, and chukar. If you want to hunt these challenging quarry with your goshawk, your experience will be aided by',
        choice1: "a good pointing dog.",
        choice2: "a good flushing dog.",
        choice3: "a large group of people beating the brush.",
        choice4: "only a and b above.",
        answer: 4,
    },
    {
        question: 'Like most activities, falconry has its own language and jargon. Some of these terms are as old as the sport itself—others are more modern. A slip is best described as',
        choice1: "chance at quarry.",
        choice2: "release of a short wing after quarry.",
        choice3: "the flight of a short wing after quarry.",
        choice4: "all of the above.",
        answer: 2,
    },
    {
        question: 'You have just witnessed a classic falconry scene: a falcon has dropped at great speed from an enormous height and struck its quarry with a “closed fist” knocking it to the ground. What is the falconry term for what a typical falcon does next?',
        choice1: "Rake away.",
        choice2: "Throw-up.",
        choice3: "Cast.",
        choice4: "Stoop.",
        answer: 2,
    },
    {
        question: 'As noted above, a decent pointing dog is a tremendous asset to a falconer hunting upland game birds with a goshawk. Typically, a pheasant will be most likely taken by a goshawk',
        choice1: "on the first flush.",
        choice2: "in the morning.",
        choice3: "on a re-flush.",
        choice4: "after sunset.",
        answer: 3,
    },
    {
        question: 'Preparation is essential for success and safety in falconry. Responsible falconers',
        choice1: "ignore the regulations, hunting seasons, and likely quarry habitat.",
        choice2: "have learned about the natural history of the species available to hunt.",
        choice3: " know both their own and their birds’ capabilities, natural tendencies and needs, as well as the limitations of each.",
        choice4: "both b and c above.",
        answer: 4,
    },
    {
        question: 'You’ve trapped your second red-tailed hawk as an apprentice, but you’ve never seen a bird act quite so tame just one day off the trap. Shouldn’t it be more wary of you this early in the training process? You decide to',
        choice1: "frighten the bird, so it’s afraid of you and behaving more “normal.”",
        choice2: "take it hunting—if it’s already this tame it is bound to be ready to fly free.",
        choice3: "release it and trap a different bird.",
        choice4: "call your sponsor and follow his/her suggestions.",
        answer: 4,
    },
    {
        question: 'Part of the apprenticeship is not having to take full responsibility for the bird you trap and train. It’s my sponsor’s job to assume authority for my bird’s health and security.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 2,
    },
    {
        question: 'Any apprentice with a valid falconry permit in Virginia can use their bird in education- al presentations to enlighten the public about the sport and the natural history of rap- tors under the following conditions:',
        choice1: "only if the group is a nonprofit and only if they’ve invited me and my bird to be there.",
        choice2: "only if the group is made up of other falconers and pre-apprentices.",
        choice3: "only under the supervision of a general or master falconry permittee.",
        choice4: "only with the written permission of my sponsor.",
        answer: 3,
    },
    {
        question: 'Apprentices are required, according to Virginia’s falconry regulations, to release their wild-caught RTH or AK after one hunting season.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 2,
    },
    {
        question: 'Going into this adventure, you’re aware that the apprenticeship will take up two long years of your life. You know it won’t be any less that 2 years, but it might take longer. What conditions must be met for the VDWR to issue your “graduate-level” permit to practice falconry at the general permittee level?',
        choice1: "You must have documents showing you asked permissions from 10 or 12 landowners to fly your bird(s) on their property, whether they allowed you to do so or not.",
        choice2: "You must maintain, train, fly, and hunt raptor(s) for a minimum of 4 months during each of your two apprentice years.",
        choice3: "Your sponsor must submit a letter to the VDWR Permit Office acknowledging that he/she feels you have achieved enough experience to “graduate” from your apprenticeship.",
        choice4: "Only b and c above are correct.",
        answer: 4,
    },
    {
        question: 'The regulations defining the sport in falconry have been developed and adopted by the Commonwealth of VA, were developed with falconers in mind and with the input of falconers. Knowing this, the regs say that you may recapture a falconry bird you have lost',
        choice1: "within one week.",
        choice2: "within one month.",
        choice3: "at any time.",
        choice4: "never.",
        answer: 3,
    },
    {
        question: 'While falconers must always be certain of the age and species of the bird they are attempting to trap, mistakes happen. If you capture one not allowed',
        choice1: "you must give the bird to another falconer who is able to possess it.",
        choice2: "you must release it immediately.",
        choice3: "you can request in writing to receive an exception from the DWR.",
        choice4: "you are required to immediately report the capture to the USFWS office nearest your home.",
        answer: 2,
    },
    {
        question: 'CFR 21.29 (e) #9 (ii) reads (in part) as follows: “If the species you wish to release is native to [your state] and is captive-bred, you may NOT release the bird to the wild unless you have permission from the State. . . If you are permitted to do so, you must hack the bird (allow it to adjust) to the wild at an appropriate time and location . . . and report release of the bird by entering the required information . . . by submitting a paper form 3-186A to your State, tribal, or territorial agency that governs falconry.” Among the definitions listed below, which best describes the concept of “hacking”?',
        choice1: "Introducing a falconry raptor to game.",
        choice2: "Releasing a passage to fly free.",
        choice3: "Allowing a young bird to mature in a chamber.",
        choice4: "None of the above.",
        answer: 4,
    },
    {
        question: 'In falconry, weight management is a key aspect of all interactions between the falconer and his/her bird. Every bird is different and weight management begins anew with each new bird in our care. Most important to training and hunting a raptor is find- ing that individual bird’s “flight weight,” which is also called its “response weight” and its “motivated weight.” All of these refer to that exact weight the bird must attain to be motivated to”fly” after game, “respond” to flushed game, or be “motivated” to hunt and feed itself. Knowing this, a beginner can understand that bird’s flight weight',
        choice1: "stays constant at all times.",
        choice2: "may vary based on temperature.",
        choice3: "is best maintained with a diet of washed meat.",
        choice4: "a and c above.",
        answer: 2,
    },
    {
        question: 'A lure is a tool the falconer can use to regain control of the bird in the field. Falcon- ers use a lure in an emergency; as a reward for a hunt well undertaken (but unsuc- cessful); and to trade a bird off its kill. Whatever the lure looks like, it includes an edible reward for the bird. That said, complete this sentence: A lure used in falconry can be',
        choice1: "a dead pigeon.",
        choice2: "sewn leather with meat attached.",
        choice3: "a bundle of wings attached together.",
        choice4: "any of the above.",
        answer: 4,
    },
    {
        question: 'The last training stage before free flight involves using a long line used in such a way as to give the bird plenty of flying room but still allowing maintenance of control by the falconer. The tool for this aspect of training is called a creance, and can be em- ployed in a variety of ways. A creance is best',
        choice1: "used in open spaces.",
        choice2: "used in thick cover.",
        choice3: "attached to the birds wing.",
        choice4: "thin and breakable.",
        answer: 1,
    },
    {
        question: 'There are a variety of styles of raptor traps available to licensed falconers. Some have eons of tradition, although the modern components of the old-style devices are made with updated materials. Others are modeled on traps used by other permitted trappers like bird banders. The most effective trap for obtaining your first red-tail is going to be which of the following?',
        choice1: "The dho-gazza.",
        choice2: "The phai-trap.",
        choice3: "The bal-chatri.",
        choice4: "The mist net.",
        answer: 3,
    },
    {
        question: 'While the mechanics of trapping aren’t terribly difficult, it is intimidating for the first-timer. Before you begin, however, it is a great idea to have certain tools with you when you begin, such as socks (nylon hose) feather-mite spray, and removable an- klets (to temporarily secure jesses and leash). Also when trapping your first hawk, you should',
        choice1: "trap alone to learn the ropes.",
        choice2: "scout an area prior to beginning.",
        choice3: "be supervised by your sponsor.",
        choice4: "b and c are advisable.",
        answer: 4,
    },
    {
        question: 'Falconry has many long traditions. Over time, the participants in the sport have come up with phrases to describe the life stages of wild-caught and captive-bred raptors used in falconry. But these phrases all have basis in natural history and raptor ecology and biology. A wild haggard falcon',
        choice1: "represents wild breeding stock.",
        choice2: "is considered more difficult to train than a passager.",
        choice3: "is unsafe to handle.",
        choice4: "a. and b. above.",
        answer: 4,
    },
    {
        question: 'The ultimate goal of manning is to gently and continuously ease the bird into new situations and introduce it to foreign objects. A good technique is to walk around with your bird-in-training and if you see something that is apparently making it nervous, turn from the object so your body is between you and the bird. This will help build the bird’s trust in you—that you will protect it from dangers. While your bird will always be “wild,” a trusting bird is less likely to stress-out and become susceptible to Aspergillosis. Your ultimate objective when training your hawk is',
        choice1: "to make it behave calm, (apparently) “tame,” and trusting in many environments.",
        choice2: "train it to accept you as its owner and master.",
        choice3: "show it affection so that it will like you.",
        choice4: "none of the above.",
        answer: 1,
    },
    {
        question: 'Some of falconry’s “jargon” actually makes logical sense. A bird that is “keen” could also be said to be',
        choice1: "hungry.",
        choice2: "sharp-set.",
        choice3: "ready to kill.",
        choice4: "all of the above.",
        answer: 4,
    },
    {
        question: 'All training is manning and all manning is training. Manning your newly-caught red- tail is best accomplished',
        choice1: "outdoors from day one.",
        choice2: "by starving weight off quickly.",
        choice3: "using food to encourage a response.",
        choice4: "by feeding a full crop daily.",
        answer: 3,
    },
    {
        question: 'Small raptors have a highly developed “flight” reaction as a response to danger or uncomfortable situations. When a raptor eats (frequently in the open on the ground) it is vulnerable to attack. We’ve learned that kestrels tend to carry their kills to a safe location to eat. To help prevent this you should',
        choice1: "use a lightweight lure.",
        choice2: "only fly it when it is in yarak.",
        choice3: "use a weighted lure line.",
        choice4: "use a halsband while flying.",
        answer: 3,
    },
    {
        question: 'You have chosen to use the waking method of early-stage training of your new bird. Once your freshly caught red-tail tires of bating off the fist and sits quietly, your next goal should be to',
        choice1: "enter it on wild game.",
        choice2: "lure fly it.",
        choice3: "get it to feed off the fist.",
        choice4: "tie it to your block perch.",
        answer: 3,
    },
    {
        question: 'There are many tools and tips available to you in learning the sport of falconry. Most will be conveyed to you and modeled for you by your sponsor. Among the most important tools we use is a lure. Use of a lure may be desired when',
        choice1: "a bird is being trained.",
        choice2: " an immediate recall of your bird is necessary.",
        choice3: "recalling your bird from a great distance.",
        choice4: "all of the above.",
        answer: 4,
    },
    {
        question: 'Whatever method of training your sponsor has taught you, you arrive at the stage where your red-tail is well manned and flying to the fist on a creance. When do you feel comfortable flying it free?',
        choice1: "When it quickly comes 10 feet to the fist.",
        choice2: "When it quickly comes 10 feet to the lure.",
        choice3: "When it quickly comes 50 feet to the lure.",
        choice4: "When it quickly comes 50 yards to the fist.",
        answer: 4,
    },
    {
        question: 'It is a very exciting time when you trap your bird and begin introducing it to your life. But first, you check for signs of ill health or other problems the bird might have straight off the trap. You notice that your newly-trapped passage has lice crawling on its feathers. You should',
        choice1: "administer IV ivermectin.",
        choice2: "release the bird as it is not likely to fly long distances.",
        choice3: "transport the bird to the nearest raptor veterinarian for extensive therapy.",
        choice4: "treat the bird with two percent Sevin dust.",
        answer: 4,
    },
    {
        question: 'Just like hunting behaviors vary between falcons and hawks, the methods we em- ploy to help our raptors get fit and athletic differ also. Your HH or RTH needs to convert some fat to muscle, and one of the best ways to do this is through an operant condi- tioning technique best described below by which choice?',
        choice1: "Pinching your birds toe when it refuses to jump to the fist.",
        choice2: "Jump-ups to the fist with a varying reward.",
        choice3: "Withholding food after not jumping to the fist.",
        choice4: "None of the above.",
        answer: 2,
    },
    {
        question: 'You may release any falconry bird back to the wild and are not required to follow State or territorial and Federal laws and regulations before the release.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 2,
    },
    {
        question: 'Among the arsenal of tools available to us in the sport is the hood, which covers the eyes of a diurnal raptor and helps keep it calm by shutting out input from these incredibly visually-oriented species. When training your first red-tail, your objective with hooding should be',
        choice1: "to be patient, calm, relaxed, and give it a good try.",
        choice2: "to only use the giant hood.",
        choice3: "to resign yourself to having a hood-shy bird.",
        choice4: "a and c above.",
        answer: 1,
    },
    {
        question: 'We talk frequently about using the lure in training a new bird, and for re-capturing a lost bird. The prime benefit, however, of using a lure with any bird includes which (if any) of the following?',
        choice1: "It will encourage your bird to tail-chase.",
        choice2: "It carries no diseases your bird can catch.",
        choice3: "There is no benefit to its use.",
        choice4: "None of the above.",
        answer: 4,
    },
    {
        question: '“Entering” your new bird is best described as',
        choice1: "serving pigeons to your long wing.",
        choice2: "giving your bird an easy chance to chase a new quarry.",
        choice3: "an ancient practice now deemed unnecessary.",
        choice4: "none of the above.",
        answer: 2,
    },
    {
        question: 'Raptors removed from the wild for falconry are always considered “wild.”',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 1,
    },
    {
        question: 'Whether mistakenly lost or intentionally released, your passage red-tailed hawk is most likely to do one of the following when on its own:',
        choice1: "look for new people to hunt with.",
        choice2: "revert back to the wild very quickly.",
        choice3: "return to its mews or weathering enclosure, where it feels comfortable and safe.",
        choice4: "starve if it is not recovered within 3 days.",
        answer: 2,
    },
    {
        question: 'You’ve hunted your red-tail for a season and it did really great. You discuss with your sponsor whether it’s a good idea to keep the bird through the molt. You agree to intermew, so your goal should be to:',
        choice1: "maintain its hunting weight (“sharp-set”) during the entire molt.",
        choice2: "enseam your bird through the molt.",
        choice3: "add ~20% to its flying weight.",
        choice4: "feed your bird as much as it can eat every day.",
        answer: 3,
    },
    {
        question: 'Which of the following terms does NOT describe a portion of a raptor’s wing?',
        choice1: "Coverts",
        choice2: "Cere",
        choice3: "Alula",
        choice4: "Secondaries",
        answer: 2,
    },
    {
        question: 'Feathers are essentially “dead” once they’ve completed growing. But good nutrition is essential for growing feathers because:',
        choice1: "hormones are essential to make them grow.",
        choice2: "a fat bird grows feathers more quickly than a thin bird.",
        choice3: "an intermewed hawk will get increasing nutrition as the days grow longer during the summer.",
        choice4: "blood circulates through a growing feather and supplies nutrients for proper growth.",
        answer: 4,
    },
    {
        question: 'A broken feather will molt more quickly than an unbroken feather because it is damaged and needs to be replaced sooner than the others.',
        choice1: "True",
        choice2: "False",
        choice3: "",
        choice4: "",
        answer: 2,
    },
]

const SCORE_POINTS = 1
const MAX_QUESTIONS = 20

startGame = () => {
    questionCounter = 0
    score = 0
    availableQuestions = [...questions]
    getNewQuestion()
}

getNewQuestion = () => {
    if(availableQuestions.length === 0 || questionCounter === MAX_QUESTIONS) {
        localStorage.setItem('mostRecentScore', score)
        return window.location.assign('https://marevkeeley.github.io/Falconerquiz/end.html')
    }
    questionCounter++
    progressText.innerText = `Question ${questionCounter} of ${MAX_QUESTIONS}`

    const questionIndex = Math.floor(Math.random() * availableQuestions.length)
    currentQuestion = availableQuestions[questionIndex]
    question.innerText = currentQuestion.question

    choices.forEach(choice =>  {
        const number = choice.dataset['number']
        choice.innerText = currentQuestion['choice' + number]
    })
    currentAnswer = currentQuestion.answer
    availableQuestions.splice(questionIndex, 1)
    acceptingAnswers = true
}

choices.forEach(choice => {
    choice.addEventListener('click', (e) => {
        if(!acceptingAnswers) return
        acceptingAnswers = false

        const selectedChoice = e.currentTarget
        const selectedAnswer = selectedChoice.dataset['number']
        let classToApply = selectedAnswer == currentQuestion.answer ? 'correct' : 'incorrect'
        selectedChoice.parentElement.classList.add(classToApply)
        if(classToApply === 'correct') {
            incrementScore(SCORE_POINTS)
            setTimeout(() => {
                selectedChoice.parentElement.classList.remove(classToApply)
                getNewQuestion()
            }, 1000)
        }
        else {
            let rightAnswer = currentQuestion.answer.dataset['number']
            rightAnswer.parentElement.classList.add('correct')
            setTimeout(() => {
                selectedChoice.parentElement.classList.remove(classToApply)
                rightAnswer.parentElement.classList.remove('correct')
                getNewQuestion()
            }, 1000)
        }
    })
})

incrementScore = num => {
    score += num
    scoreText.innerText = score
}

startGame()
